version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./htdocs:/var/www/html
    depends_on:
      - db
  db:
    image: mysql:5.5.62
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=courses_portal
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=mypassword
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db:mysql
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=mypassword

